name: run-tests-on-pull-request-creation
run-name: ${{ github.actor }} created a PR
on: [pull_request, workflow_dispatch]
jobs:
  run-tests:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm install
      - name: Create .env file
        run: |
          echo "LOGINNAME=$LOGINNAME" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "PASSWORD=$PASSWORD" | Out-File -FilePath $env:GITHUB_ENV -Append
        env:
          LOGINNAME: ${{ vars.LOGINNAME }}
          PASSWORD: ${{ vars.PASSWORD }}
      - name: Run tests
        run: npm run wdio-local
