name: run-tests-on-pull-request-creation
run-name: ${{ github.actor }} created a PR
on: [pull_request, workflow_dispatch]
jobs:
  run-tests:
    runs-on: windows-latest
    env:
      LOGINNAME: ${{ vars.LOGINNAME }}
      PASSWORD: ${{ vars.PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm install
      - name: Create env file
        run: |
          touch .env
          echo LOGINNAME="$LOGINNAME" >> .env
          echo PASSWORD="$PASSWORD" >> .env
          cat .env
      - name: Run tests
        run: npm run wdio-local
