name: run-tests-on-pull-request-creation
run-name: ${{ github.actor }} created a PR
on: [pull_request, workflow_dispatch]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK for reporting
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm install
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1.5.0
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0.3
        with:
          envkey_LOGINNAME: ${{ secrets.LOGINNAME }}
          envkey_PASSWORD: ${{ secrets.PASSWORD }}
      - name: Run tests
        run: npm run wdio-local
      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: main
          path: main
      - name: Build test report
        uses: simple-elf/allure-report-action@v1.8
        if: always()
        with:
          gh_pages: main
          allure_history: allure-history
          allure_results: allure-results
      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3.9.3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: main
          publish_dir: allure-history
